# version: '3.9'

services:
  db:
    image: postgres:14-alpine
    container_name: postgres
    ports:
      - 5432:5432
    env_file: .env
    environment:
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_USER: '${POSTGRES_LOGIN}'
      POSTGRES_DB: '${POSTGRES_NAME}'
    restart: always